
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Name of the User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     * @throws java.lang.ClassNotFoundException
     */
    
    String allergy = "";
    ButtonGroup bg;
    String ip;
    String remote = "192.168.1.20";
    
    public MainForm() throws ClassNotFoundException {
        this.ip = JOptionPane.showInputDialog(null, "Enter Remote Machine Address: ");
        if (!ip.equals(this.remote)) {
            JOptionPane.showMessageDialog(null, "Wrong remote address, Program Terminated. ", "NYC 2017 Registration", ERROR_MESSAGE);
            System.exit(0);
        }
        else {
            JOptionPane.showMessageDialog(null, "Connected Successfully ", "NYC 2017 Registration", INFORMATION_MESSAGE);
            initComponents();
            groupButton();
            MainPanel.requestFocusInWindow();
            Test.GhostText name = new Test.GhostText(tfl_name, "Example: Rezane, Warren D.");
            Test.GhostText campsattended = new Test.GhostText(tfl_campsattended, "If first time, put 0.");
        }
    }
    
    private void groupButton() {
        bg = new ButtonGroup();
        bg.add(rb_male);
        bg.add(rb_female);
    }
    
    private void clearAll() {
        MainPanel.requestFocusInWindow();
        Test.GhostText name = new Test.GhostText(tfl_name, "Example: Rezane, Warren D.");
        Test.GhostText campsattended = new Test.GhostText(tfl_campsattended, "If first time, put 0.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        btn_register = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_register1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        pnl_register = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        pnl_step1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        tfl_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        tfl_age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        tfl_church = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tfl_churchpos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        tfl_churchaddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbx_district = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rb_female = new javax.swing.JRadioButton();
        rb_male = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tfl_email = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        tfl_contact = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        tfl_pastorname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        tfl_pastorcontact = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        tfl_campsattended = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chk_shrimp = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        tfl_other = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_sub = new javax.swing.JButton();
        chk_fish = new javax.swing.JCheckBox();
        chk_none = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        chk_chicken = new javax.swing.JCheckBox();
        chk_other = new javax.swing.JCheckBox();
        chk_pork = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(127, 140, 141));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_register.setBackground(new java.awt.Color(127, 140, 141));

        label.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("View Responses");

        javax.swing.GroupLayout btn_registerLayout = new javax.swing.GroupLayout(btn_register);
        btn_register.setLayout(btn_registerLayout);
        btn_registerLayout.setHorizontalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_registerLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(label)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        btn_registerLayout.setVerticalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        SidePanel.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NYC");
        SidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registration");
        SidePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2017");
        SidePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        SidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 10));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Build: v2.0 (12/22/17)");
        SidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 635, -1, -1));

        btn_register1.setBackground(new java.awt.Color(149, 165, 166));

        label1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Register");

        javax.swing.GroupLayout btn_register1Layout = new javax.swing.GroupLayout(btn_register1);
        btn_register1.setLayout(btn_register1Layout);
        btn_register1Layout.setHorizontalGroup(
            btn_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_register1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(label1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        btn_register1Layout.setVerticalGroup(
            btn_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        SidePanel.add(btn_register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        pnl_register.setBackground(new java.awt.Color(255, 255, 255));
        pnl_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel1.setText("Register");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(982, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnl_register.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1100, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pnl_register.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        btn_minimize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btn_minimize.setText("_");
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        pnl_register.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, -30, 20, 70));

        pnl_step1.setBackground(new java.awt.Color(44, 62, 80));

        tfl_name.setBackground(new java.awt.Color(44, 62, 80));
        tfl_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_name.setForeground(new java.awt.Color(255, 255, 255));
        tfl_name.setToolTipText("");
        tfl_name.setBorder(null);
        tfl_name.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        tfl_age.setBackground(new java.awt.Color(44, 62, 80));
        tfl_age.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_age.setForeground(new java.awt.Color(204, 204, 204));
        tfl_age.setBorder(null);
        tfl_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfl_ageKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("District:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name of Local Church:");

        tfl_church.setBackground(new java.awt.Color(44, 62, 80));
        tfl_church.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_church.setForeground(new java.awt.Color(204, 204, 204));
        tfl_church.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Church Position:");

        tfl_churchpos.setBackground(new java.awt.Color(44, 62, 80));
        tfl_churchpos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_churchpos.setForeground(new java.awt.Color(204, 204, 204));
        tfl_churchpos.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Church Address:");

        tfl_churchaddress.setBackground(new java.awt.Color(44, 62, 80));
        tfl_churchaddress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_churchaddress.setForeground(new java.awt.Color(204, 204, 204));
        tfl_churchaddress.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Age:");

        cbx_district.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbx_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Agusan District", "Bukidnon", "Cebu", "CENODA District", "COMVAL District", "Cotabato 1 (North)", "Cotabato 2", "Davao City", "Davao Del Sur", "Emmanuel District", "MANA District", "Maranatha District", "Monkayo District", "NEDA District ", "Samal (IGACOS) District", "Sarangani District", "SOCSARGEN District", "Valenzuela City", "Zampen District", "Bohol" }));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");

        rb_female.setBackground(new java.awt.Color(44, 62, 80));
        rb_female.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rb_female.setForeground(new java.awt.Color(255, 255, 255));
        rb_female.setText("Female");

        rb_male.setBackground(new java.awt.Color(44, 62, 80));
        rb_male.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        rb_male.setForeground(new java.awt.Color(255, 255, 255));
        rb_male.setText("Male");

        javax.swing.GroupLayout pnl_step1Layout = new javax.swing.GroupLayout(pnl_step1);
        pnl_step1.setLayout(pnl_step1Layout);
        pnl_step1Layout.setHorizontalGroup(
            pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_step1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel21))
                    .addComponent(tfl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel22))
                    .addComponent(tfl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23)
                        .addGap(19, 19, 19)
                        .addComponent(rb_male)
                        .addGap(35, 35, 35)
                        .addComponent(rb_female))
                    .addComponent(jLabel11)
                    .addComponent(tfl_church, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tfl_churchpos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfl_churchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addComponent(cbx_district, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)))
                .addGap(0, 0, 0))
        );
        pnl_step1Layout.setVerticalGroup(
            pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_step1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel22)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_age, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23)
                    .addComponent(rb_male)
                    .addComponent(rb_female))
                .addGap(11, 11, 11)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_church, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_churchpos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pnl_step1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_churchaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addGap(19, 19, 19)
                .addGroup(pnl_step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        pnl_register.add(pnl_step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, 560));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Email:");

        tfl_email.setBackground(new java.awt.Color(44, 62, 80));
        tfl_email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_email.setForeground(new java.awt.Color(204, 204, 204));
        tfl_email.setBorder(null);

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Contact no.:");

        tfl_contact.setBackground(new java.awt.Color(44, 62, 80));
        tfl_contact.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_contact.setForeground(new java.awt.Color(204, 204, 204));
        tfl_contact.setBorder(null);
        tfl_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfl_contactKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Youth Pastor/Local Pastor:");

        tfl_pastorname.setBackground(new java.awt.Color(44, 62, 80));
        tfl_pastorname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_pastorname.setForeground(new java.awt.Color(204, 204, 204));
        tfl_pastorname.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Youth Pastor/Local Pastor Contact no.:");

        tfl_pastorcontact.setBackground(new java.awt.Color(44, 62, 80));
        tfl_pastorcontact.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_pastorcontact.setForeground(new java.awt.Color(204, 204, 204));
        tfl_pastorcontact.setBorder(null);
        tfl_pastorcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfl_pastorcontactKeyTyped(evt);
            }
        });

        tfl_campsattended.setBackground(new java.awt.Color(44, 62, 80));
        tfl_campsattended.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfl_campsattended.setForeground(new java.awt.Color(204, 204, 204));
        tfl_campsattended.setBorder(null);
        tfl_campsattended.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfl_campsattendedKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No. of Camps Attended:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(tfl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(tfl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfl_pastorname, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfl_pastorcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfl_campsattended, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_pastorname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_pastorcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tfl_campsattended, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pnl_register.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 350, 560));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        chk_shrimp.setBackground(new java.awt.Color(44, 62, 80));
        chk_shrimp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_shrimp.setForeground(new java.awt.Color(255, 255, 255));
        chk_shrimp.setText("Shrimp");
        chk_shrimp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_shrimpMouseClicked(evt);
            }
        });

        tfl_other.setBackground(new java.awt.Color(44, 62, 80));
        tfl_other.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfl_other.setForeground(new java.awt.Color(255, 255, 255));
        tfl_other.setBorder(null);
        tfl_other.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Food Preference:");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Allergies:");

        btn_sub.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btn_sub.setText("SUBMIT");
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });

        chk_fish.setBackground(new java.awt.Color(44, 62, 80));
        chk_fish.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_fish.setForeground(new java.awt.Color(255, 255, 255));
        chk_fish.setText("Fish");
        chk_fish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_fishMouseClicked(evt);
            }
        });

        chk_none.setBackground(new java.awt.Color(44, 62, 80));
        chk_none.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_none.setForeground(new java.awt.Color(255, 255, 255));
        chk_none.setText("None");
        chk_none.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_noneMouseClicked(evt);
            }
        });

        jCheckBox5.setBackground(new java.awt.Color(44, 62, 80));
        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("None");

        chk_chicken.setBackground(new java.awt.Color(44, 62, 80));
        chk_chicken.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_chicken.setForeground(new java.awt.Color(255, 255, 255));
        chk_chicken.setText("Chicken");
        chk_chicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_chickenMouseClicked(evt);
            }
        });

        chk_other.setBackground(new java.awt.Color(44, 62, 80));
        chk_other.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_other.setForeground(new java.awt.Color(255, 255, 255));
        chk_other.setText("Other:");
        chk_other.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_otherMouseClicked(evt);
            }
        });

        chk_pork.setBackground(new java.awt.Color(44, 62, 80));
        chk_pork.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        chk_pork.setForeground(new java.awt.Color(255, 255, 255));
        chk_pork.setText("Pork");
        chk_pork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_porkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel24))
                    .addComponent(chk_none)
                    .addComponent(jCheckBox5)
                    .addComponent(chk_fish)
                    .addComponent(chk_chicken)
                    .addComponent(chk_shrimp)
                    .addComponent(chk_pork)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(chk_other)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfl_other, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_none)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addComponent(chk_fish)
                .addGap(18, 18, 18)
                .addComponent(chk_chicken)
                .addGap(18, 18, 18)
                .addComponent(chk_shrimp)
                .addGap(18, 18, 18)
                .addComponent(chk_pork)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_other)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfl_other, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pnl_register.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 380, 560));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 268, Short.MAX_VALUE)
                .addComponent(pnl_register, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(pnl_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chk_porkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_porkMouseClicked
        if (chk_pork.isSelected()) {
            this.allergy += "Pork ";
            chk_none.setEnabled(false);
        }
        else if (chk_pork.isSelected() == false) {
            this.allergy = this.allergy.replace("Pork ", "");
            chk_none.setEnabled(true);
        }
    }//GEN-LAST:event_chk_porkMouseClicked

    private void chk_otherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_otherMouseClicked
        String other = tfl_other.getText();
        if (chk_other.isSelected()) {
            tfl_other.setEnabled(true);
            chk_none.setEnabled(false);
        }
        else if (chk_other.isSelected() == false) {
            this.allergy = this.allergy.replace(other, "");
            tfl_other.setEnabled(false);
            chk_none.setEnabled(true);
            tfl_other.setText("");
        }
    }//GEN-LAST:event_chk_otherMouseClicked

    private void chk_chickenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_chickenMouseClicked
        if (chk_chicken.isSelected()) {
            this.allergy += "Chicken ";
            chk_none.setEnabled(false);
        }
        else if (chk_chicken.isSelected() == false) {
            this.allergy = this.allergy.replace("Chicken ", "");
            chk_none.setEnabled(true);
        }
    }//GEN-LAST:event_chk_chickenMouseClicked

    private void chk_noneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_noneMouseClicked
        if (chk_none.isSelected()) {
            this.allergy += "None ";
            chk_chicken.setEnabled(false);
            chk_shrimp.setEnabled(false);
            chk_fish.setEnabled(false);
            chk_pork.setEnabled(false);
            chk_other.setEnabled(false);
        }
        else if (chk_none.isSelected() == false) {
            this.allergy = this.allergy.replace("None ", "");
            chk_chicken.setEnabled(true);
            chk_shrimp.setEnabled(true);
            chk_fish.setEnabled(true);
            chk_pork.setEnabled(true);
            chk_other.setEnabled(true);
        }
    }//GEN-LAST:event_chk_noneMouseClicked

    private void chk_fishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_fishMouseClicked
        if (chk_fish.isSelected()) {
            this.allergy += "Fish ";
            chk_none.setEnabled(false);
        }
        else if (chk_fish.isSelected() == false) {
            this.allergy = this.allergy.replace("Fish ", "");
            chk_none.setEnabled(true);
        }
    }//GEN-LAST:event_chk_fishMouseClicked

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        String name = tfl_name.getText();
        String age = tfl_age.getText();
        String gender = null;
        if (rb_male.isSelected()) {
            gender = "Male";
        }
        else if (rb_female.isSelected()) {
            gender = "Female";
        }
        String churchName = tfl_church.getText();
        String churchPos = tfl_churchpos.getText();
        String churchAdd = tfl_churchaddress.getText();
        String district = cbx_district.getSelectedItem().toString();
        String email = tfl_email.getText();
        String contact = tfl_contact.getText();
        String pastorName = tfl_pastorname.getText();
        String pastorContact = tfl_pastorcontact.getText();
        String campsAttended = tfl_campsattended.getText();
        this.allergy += tfl_other.getText();
        if (name.isEmpty() && age.isEmpty() && gender.isEmpty() && district.isEmpty() && this.allergy.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Complete All Required Fields!", "Register", ERROR_MESSAGE);

        }
        else if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Name!", "Register", ERROR_MESSAGE);

        }
        else if (age.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Age!", "Register", ERROR_MESSAGE);

        }
        else if (gender.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select Your Gender!", "Register", ERROR_MESSAGE);

        }
        else if (district.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select Your District!", "Register", ERROR_MESSAGE);

        }
        else if (this.allergy.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Select Your Food Preference!", "Register", ERROR_MESSAGE);

        }
        else {
            try {
                Contact campContact = new Contact(name,age,gender,churchName,churchPos,churchAdd,district,email,contact,pastorName,pastorContact,campsAttended,this.allergy);
                UserDB udb = new UserDB(this.ip);
                boolean valid = udb.validate(campContact);
                if (valid) {
                    JOptionPane.showMessageDialog(null, "Contact Information Successfully Added.", "NYC 2017 Registration", INFORMATION_MESSAGE);
                    tfl_name.setText("");
                    tfl_age.setText("");
                    bg.clearSelection();
                    tfl_church.setText("");
                    tfl_churchaddress.setText("");
                    tfl_churchpos.setText("");
                    cbx_district.setSelectedIndex(0);
                    tfl_email.setText("");
                    tfl_contact.setText("");
                    tfl_pastorname.setText("");
                    tfl_pastorcontact.setText("");
                    tfl_campsattended.setText("");
                    this.allergy = "";
                    gender = "";
                    chk_chicken.setSelected(false);
                    chk_shrimp.setSelected(false);
                    chk_pork.setSelected(false);
                    chk_none.setSelected(false);
                    chk_fish.setSelected(false);
                    chk_other.setSelected(false);
                    chk_chicken.setEnabled(true);
                    chk_shrimp.setEnabled(true);
                    chk_fish.setEnabled(true);
                    chk_pork.setEnabled(true);
                    chk_other.setEnabled(true);
                    chk_none.setEnabled(true);
                    tfl_other.setText("");
                    tfl_other.setEnabled(false);
                    clearAll();
                }
                else {
                    JOptionPane.showMessageDialog(null, "There's something wrong with your data.", "NYC 2017 Registration", ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_subActionPerformed

    private void chk_shrimpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_shrimpMouseClicked
        if (chk_shrimp.isSelected()) {
            this.allergy += "Shrimp ";
            chk_none.setEnabled(false);
        }
        else if (chk_shrimp.isSelected() == false) {
            this.allergy = this.allergy.replace("Shrimp ", "");
            chk_none.setEnabled(true);
        }
    }//GEN-LAST:event_chk_shrimpMouseClicked

    private void tfl_campsattendedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfl_campsattendedKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_tfl_campsattendedKeyTyped

    private void tfl_pastorcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfl_pastorcontactKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_tfl_pastorcontactKeyTyped

    private void tfl_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfl_contactKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_tfl_contactKeyTyped

    private void tfl_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfl_ageKeyTyped
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar)
            || (vChar == KeyEvent.VK_BACK_SPACE)
            || (vChar == KeyEvent.VK_DELETE))) {
        evt.consume();
        }
    }//GEN-LAST:event_tfl_ageKeyTyped

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you wanna exit?", "NYC 2017 Registration", WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        else {

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JPanel btn_register;
    private javax.swing.JPanel btn_register1;
    private javax.swing.JButton btn_sub;
    private javax.swing.JComboBox<String> cbx_district;
    private javax.swing.JCheckBox chk_chicken;
    private javax.swing.JCheckBox chk_fish;
    private javax.swing.JCheckBox chk_none;
    private javax.swing.JCheckBox chk_other;
    private javax.swing.JCheckBox chk_pork;
    private javax.swing.JCheckBox chk_shrimp;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JPanel pnl_step1;
    private javax.swing.JRadioButton rb_female;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField tfl_age;
    private javax.swing.JTextField tfl_campsattended;
    private javax.swing.JTextField tfl_church;
    private javax.swing.JTextField tfl_churchaddress;
    private javax.swing.JTextField tfl_churchpos;
    private javax.swing.JTextField tfl_contact;
    private javax.swing.JTextField tfl_email;
    private javax.swing.JTextField tfl_name;
    private javax.swing.JTextField tfl_other;
    private javax.swing.JTextField tfl_pastorcontact;
    private javax.swing.JTextField tfl_pastorname;
    // End of variables declaration//GEN-END:variables
}
